### ISSUE TITLE
👏ALWAYS👏 COMMENT 👏YOUR👏CODE

### ISSUE THREAD

**Issue by stopmotio** [PolyMarsDev/Terri-Fried#17]
Okay, so, obnoxious title aside, you broke the first rule of programming, and also **makes contributing significantly more difficult**. AFAIK this looks done and dusted, but, don't ever do this again.

**Comment by mandar1jn** [comment]
@stopmotio this code was written for a game jam and after that just for a challenge. I get why he didn’t comment his code.

**Comment by stopmotio** [comment]
@mandar1jn it wouldn't take that much effort and it just makes it easier. He had 3 days, it would be easier if he just commented from the beginning.

**Comment by mandar1jn** [comment]
As someone who has participated in game jams myself: in this short of a time span you will remember what your code does. If you name your variables, functions and classes correctly it will cost more time to write meaningful comments then it will take you to look up what some piece of coded does now and then. It also depends on your preference. I myself don’t like commenting my code because it costs more time when scanning through your code because comments distract me. It also depends on if you are working in a group or solo. If you are working soli there is less ned for comments then when you are working in a group.

**Comment by stopmotio** [comment]
Besides that, it's gotten pull requests merged which makes the fact that it's still a commentless mess is more poignant. Even in that environment I can't imagine writing a few words for each hundred lines would be that hard unless you have terrible wpm.

**Comment by mandar1jn** [comment]
Well, the code is written quite clearly and if you read the names of variables, classes and functions you will be able to figure it out

**Comment by stopmotio** [comment]
Oh cool. Closing then. Probably saw the commentless code and had an anxiety flare. My bad, don't let me justify this with that.
